### ISSUE TITLE
Double Clippings Records

### ISSUE THREAD

**Issue by alexxanthoudakis** [sfu-dhil/circus#22]
**Describe the bug**
There are double records that show up on the Clippings page. 

**To Reproduce**
1. Go to Clippings from the Circus home page
2. Take note of:
- IMG_8474 1 and 2
- IMG_8485
- IMG_3414
- IMG_3426
- IMG_3266
- IMG_3268
- IMG_4743
- IMG_8563
3. Click through to page 2
4. See duplicates

**Expected behavior**
No duplicates!

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Additional context**
This problem persists on page 3. All records below can be found on page 1 and page 3.
- IMG_8474 1 and 2
- IMG_8485
- IMG_8498
- IMG_8499
- IMG_8583
- IMG_3414
- IMG_4655
- IMG_3426
- IMG_3468
- IMG_3303

**Comment by joeytakeda** [comment]
After discussion with LD, we determined that these aren't necessarily duplicates, but the same image used for a number of records. Sometimes, when clippings are particularly short, one image was taken of multiple clippings and so that image is then used in various clippings. By fixing #20 , this issue is resolved, I think.
