### ISSUE TITLE
Provide an easy way for users to access the Category Page

### ISSUE THREAD

**Issue by alexxanthoudakis** [sfu-dhil/circus#24]
**Describe the bug**
Though the 'Category' tab is apparently hidden in the admin side, you can easily get to it through the Manuscript category list! Because the nav bar tab is hidden to the public, this is the only way you can get to category page.

**To Reproduce**
1. Go to Clippings.
2. Click on the first clipping.
3. Scroll down and click 'Manuscript'
3. Click the 'Back' button in the top-right corner of the page
4. This is the only way to get to the category page!

**Expected behavior**
There should be another, easily accessible way to get to this page for the public.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome

**Additional Information**
The fact that the button to get to this page is 'Back' is also a little confusing! I expected to be brought back to the record, not to the category page.

**Comment by joeytakeda** [comment]
I really dislike the "Back" button for precisely the reasons you outline above, @alexxanthoudakis. 

I think breadcrumb menus are nicer, but we'll have to figure out what the right way to do a breadcrumb menu is for this site.

A few options:

Show the category from which the thing comes and the clipping

```
Home > [[Category]] > [[ThisClipping]]
```

Or show just the clippings menu (since every clipping is of course in the Clippings index):

```
Home > Clippings > [[This Clipping]]
```
I like the first one, since people will _probably_ want to return to categories rather than an index of all the clippings (just a conjecture, tho). 

Another option, I suppose, is to construct the breadcrumb based off of how you get there, but I think stable options are better than dynamic ones in this case.

**Comment by ubermichael** [comment]
Well spotted Alex!

I think LD will probably want `Home > [[Manuscript]] > [[Clipping]]` but we should talk about it with her.

**Comment by joeytakeda** [comment]
This is now done; Categories are clickable via the video page itself, but there is also a category link in the header, which goes here: https://dhil.lib.sfu.ca/circus/category/
